@echo off
rem JBang launcher for CMD. All the actual work (finding or downloading JBang
rem and a JDK, running JBang) is done by jbang.ps1. This script only tells
rem jbang.ps1 that it is running on behalf of CMD and, when JBang asks for a
rem command to be executed (exit code 255), runs that command in this shell.
setlocal
set "JBANG_RUNTIME_SHELL=cmd"
set "JBANG_LAUNCH_CMD=%~f0"

rem execute jbang and redirect output to temporary file
rem (WARNING running jbang in parallel in quick succession will cause temp name collisions!!)
set "tmpfile=%TEMP%\%RANDOM%.jbang.tmp"
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0jbang.ps1" %* > "%tmpfile%"
set "ERROR=%ERRORLEVEL%"
if %ERROR% EQU 255 goto :execute

type "%tmpfile%"
del /f /q "%tmpfile%"
exit /b %ERROR%

:execute
rem read the command generated by jbang (first line only), delete the temporary file and execute it
set "OUTPUT="
for /f "usebackq delims=" %%L in ("%tmpfile%") do if not defined OUTPUT set "OUTPUT=%%L"
del /f /q "%tmpfile%"
%OUTPUT%
exit /b %ERRORLEVEL%
